import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from scipy.stats import entropy


# --- 1. SG-GAN ARCHITECTURE (Fig. 1) ---
class Generator(nn.Module):
    def __init__(self, noise_dim, feature_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(noise_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, feature_dim),
            nn.Tanh()  # Normalizes output to [-1, 1] as per Eq. 3
        )

    def forward(self, z):
        return self.model(z)


class Discriminator(nn.Module):
    def __init__(self, feature_dim):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(feature_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)


# --- 2. EVALUATION & VISUALIZATION TOOLS ---
def calculate_kl_divergence(real_data, generated_data):
    """Implementation of Eq. 11: KL Divergence for feature distribution"""
    # Create histograms to represent probability distributions p and q
    p, _ = np.histogram(real_data, bins=10, density=True)
    q, _ = np.histogram(generated_data, bins=10, density=True)

    # Laplace smoothing to avoid division by zero
    p += 1e-10
    q += 1e-10

    return entropy(p, q)


def visualize_generated_network(generated_coords):
    """Visualizes the spatial graph generated by G"""
    G = nx.Graph()
    coords = generated_coords.reshape(-1, 2)

    for i, (x, y) in enumerate(coords):
        G.add_node(i, pos=(x, y))
        if i > 0:  # Connecting nodes to simulate a road path
            G.add_edge(i - 1, i)

    pos = nx.get_node_attributes(G, 'pos')
    plt.figure(figsize=(6, 4))
    nx.draw(G, pos, with_labels=True, node_color='lightgreen', edge_color='black')
    plt.title("SG-GAN Generated Road Network")
    plt.show()


# --- 3. FINAL TESTING EXECUTION ---
def run_sg_gan_test():
    # Configuration
    NOISE_DIM = 10
    NUM_NODES = 10
    FEATURE_DIM = NUM_NODES * 2  # (x, y) for each node

    # Initialize Generator (netG) and Discriminator (netD)
    netG = Generator(NOISE_DIM, FEATURE_DIM)
    netD = Discriminator(FEATURE_DIM)

    # Simulate some "Real" road data for comparison (normalized)
    real_sample = np.random.uniform(-1, 1, (1, FEATURE_DIM))

    print("--- Starting SG-GAN Test ---")

    # A. Generate Fake Graph Sample
    noise = torch.randn(1, NOISE_DIM)
    fake_sample = netG(noise).detach().numpy()

    # B. Test Discriminator Output
    decision = netD(torch.tensor(fake_sample)).item()
    print(f"Discriminator confidence (Real=1, Fake=0): {decision:.4f}")

    # C. Calculate KL Divergence (Eq. 11)
    kl_score = calculate_kl_divergence(real_sample.flatten(), fake_sample.flatten())
    print(f"KL Divergence (Structural Similarity): {kl_score:.4f}")

    # D. Visualize
    visualize_generated_network(fake_sample)


# Execute
if __name__ == "__main__":
    run_sg_gan_test()